fileVersion: 1
id: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
name: V_DL_CPS_ONDEMAND_SETTINGS_CURRENT
operation:
  config:
    insertStrategy: UNION
    selectDistinct: false
  customOverride: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: DATA_LAKE
  materializationType: view
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5f432e41-804d-4fae-95fa-96debc2e38e4
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: ID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5c450e16-d1f0-4925-a240-ff5a4154030a
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9fe3dbd7-92c2-456b-92b9-cfe7f551d999
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: USERTYPE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: abe3b14f-c33e-4a22-a9b6-c19293f65907
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 65c7d1ef-5f50-46d7-b23b-12bec926ea77
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: DOMAIN
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d4b3f776-b96a-491e-bbc7-4e76bbda1255
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0fc482aa-1894-40e4-b635-5657f44da8a6
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: CUSTOMFIELD
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5ee80adf-6cff-4913-8c6c-f5a3a5daa559
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: db0500e7-da7e-4f9a-b17e-b086d99a2e7a
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ISAUDIORECORDING
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ce5e3c8a-3e35-47c3-90a9-5b29f00acca4
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 956c88ae-5fb2-46c9-8920-b57731ef5497
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ISSCREENRECORDING
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f233d0d8-dad3-4de1-831a-d832d1c46cbb
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6b7465ad-1cc2-4779-93f0-28b71d7c1e6a
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        name: EDITEDDATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f6d35eee-38ea-4473-8254-ad7947e1f7e3
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d0b700fe-8d1b-4ca4-bc63-2968148cb029
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: Record source
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e6fd5ff4-a704-4251-83e9-2ac86393425a
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 80d7f052-1949-4a79-bfce-b9b7a74d599b
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was loaded
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 185c0e42-b2b2-41d6-b94c-ce69592d56cd
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 00fa3eb3-7762-4d6d-bf91-5a12b13a3911
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: To track delted records from source system
        name: TO_BE_DELETED
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6299183d-6fe3-4623-9150-cdbde2ce8ff8
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ff79f877-fa57-498d-9500-c8125c00e9e0
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e63098f1-ffc3-4e23-b444-75f0d36c4c61
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b5c9f46f-9cec-4e2a-812b-3adec489e1b0
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ed1936fc-a853-4ff2-87c4-d356a368e866
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7d013217-6c94-45c5-949c-d7b75a725163
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: VARCHAR(3)
        defaultValue: ""
        description: ""
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b9c43124-639f-44c9-b6ec-feda4b607acd
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b8f9c606-c830-45da-bccb-936f11baa60e
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isSystemVersion: true
        name: DSS_VERSION
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d1948e13-813a-4999-8dfc-ec7b7daeb1f1
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cb7fd4d9-86b0-46f9-a1ce-9e33cd05312d
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 321bc485-3b2c-49fd-8a13-08cc8443016b
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 61d5fab5-29a1-4159-8851-ac22b8765390
          stepCounter: c82cf7eb-bac0-4f12-9f2d-d81ef1d75cf2
        config: {}
        dataType: TIMESTAMP_NTZ(9)
        defaultValue: ""
        description: ""
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d3613dc9-8ed7-473f-a2bc-50b10f4b84ff
                stepCounter: 1ad8d508-f300-4459-a453-455d482fa3cd
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          DL_CPS_ONDEMAND_SETTINGS: 1ad8d508-f300-4459-a453-455d482fa3cd
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: DATA_LAKE
            nodeName: DL_CPS_ONDEMAND_SETTINGS
        join:
          joinCondition: FROM {{ ref('DATA_LAKE','DL_CPS_ONDEMAND_SETTINGS') }} dl_cps_ondemand_settings
        name: V_DL_CPS_ONDEMAND_SETTINGS_CURRENT
        noLinkRefs: []
  name: V_DL_CPS_ONDEMAND_SETTINGS_CURRENT
  overrideSQL: false
  schema: ""
  sqlType: View
  type: sql
  version: 1
type: Node
