fileVersion: 1
id: 75b30e9e-7625-4e59-81a9-fe7c8731a839
name: DL_PCCE_APPLICATION_GATEWAY_HALF_HOU
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: DATA_LAKE
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ab70a1ce-dd68-4850-a833-79b0068a3406
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: APPLICATIONGATEWAYID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0422d15d-c0ec-4435-a38a-94dc4f0bccad
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 57d659cb-fb5b-403d-876f-d3ef7be4f597
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: TIMESTAMP(0)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: DATETIME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c0d66f42-246f-4521-b6a1-57c6895468b4
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3b50d47b-cdba-4d6a-9d1c-6a2d0f6ea176
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: TIMEZONE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 582ea58d-8d8b-454f-940c-76f3e672358a
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9b3e6a5d-3753-4859-8e27-2b6cadf91118
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: REQUESTSTOHALF
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6cf4ee6e-e45d-4d15-9bf7-c7c7c6283c9d
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5563769b-9038-47ab-abd5-a3244f60ba64
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: REJECTSTOHALF
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 91fb8612-986f-4292-8fdf-4ee870f7ef63
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6e4194f5-0e76-452d-9c7e-7412e8b58346
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: TIMEOUTSTOHALF
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 7864247d-d7dc-427d-bee3-3784f9620fc1
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ee2c042a-046a-4ec5-a1b8-ece2f0337f28
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: MAXDELAYTOHALF
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 10e9c49b-d5ae-4953-85e8-0cdc4a2699d2
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e786c1d8-021b-47a3-9f2a-93bf3c2af5ef
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: AVGDELAYTOHALF
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 564af796-8821-4f0e-a480-82c8095aea77
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4ee652df-f12c-4a0d-b517-dcf09631c20d
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: UNAVAILABLETOHALF
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 114293d1-cee3-4433-a828-5899bb5672af
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f81e517a-a344-44d6-a9b5-dfe807fc7cfd
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: ERRORSTOHALF
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 9fb8804b-04d0-45c3-81cf-88453eb7271b
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6db0aef4-915f-42a4-8fd9-9e64b41e35d8
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: DOUBLE
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: RECOVERYKEY
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8d69b917-c5ea-4e06-8837-70b95e3177a0
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: aa421857-26cc-4f20-8abb-33bb6cd04175
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: LATESTOHALF
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 63caba51-8459-4d39-9168-63386b57f608
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 87b5ccb4-b636-48a9-8930-8af2583effa4
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: DBDATETIME
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 85558701-f4c9-4239-a9f3-3bd04eced805
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cfa881ec-4b19-472d-995c-cf202488a73b
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: Record source
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 9d23e670-bd0d-44a3-8cff-8b268d7c8837
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e865d20d-f7e9-4690-bcbf-22453fbd334f
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was loaded
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 89ebf9c0-ea99-4288-9b28-55a86b2d4a14
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f82631a3-4ca8-47b1-8e7b-8e92120d5258
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: To track delted records from source system
        name: TO_BE_DELETED
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5aad5e6c-b6d2-46ef-8782-bcc335e2e58a
                stepCounter: 5eab875f-df78-4005-9fcd-7706c9015a52
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a2661511-1f41-4f3f-9b16-78bb7e70c9f1
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b8f632be-fe91-4a22-9149-a37c32a9d6b2
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9fa10476-54d2-4eab-b05d-f4ef293eace2
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: VARCHAR(3)
        defaultValue: ""
        description: ""
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7499ced8-7f9a-4cdd-b886-32a9ce76f89c
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isSystemVersion: true
        name: DSS_VERSION
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 91bcd4f8-b9ee-4de9-918d-d55d69987d53
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 88ece957-78d9-4a89-bca7-e6c87cf27141
          stepCounter: 75b30e9e-7625-4e59-81a9-fe7c8731a839
        config: {}
        dataType: TIMESTAMP_NTZ(9)
        defaultValue: ""
        description: ""
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LD_PCCE_APPLICATION_GATEWAY_HALF_HOU: 5eab875f-df78-4005-9fcd-7706c9015a52
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: DATA_LAKE
            nodeName: LD_PCCE_APPLICATION_GATEWAY_HALF_HOU
        join:
          joinCondition: FROM {{ ref('DATA_LAKE','LD_PCCE_APPLICATION_GATEWAY_HALF_HOU') }} ld_pcce_application_gateway_half_hou
        name: DL_PCCE_APPLICATION_GATEWAY_HALF_HOU
        noLinkRefs: []
  name: DL_PCCE_APPLICATION_GATEWAY_HALF_HOU
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
