fileVersion: 1
id: f50f2841-f884-4178-aa77-4064b5e1398a
name: DL_DC64_POLICYDETAILSETTINGS
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: DATA_LAKE
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 01d38a53-58d5-43e7-bce0-2ec769526ee4
          stepCounter: f50f2841-f884-4178-aa77-4064b5e1398a
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: POLICYDETAILSETTINGS_ID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 03aa45bf-ca19-49df-825f-5f2f6aab574a
                stepCounter: ae8117b4-5e98-4a14-b772-0a8e942cac9b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a46be77f-db0a-4afa-afdc-8c8885b42304
          stepCounter: f50f2841-f884-4178-aa77-4064b5e1398a
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: DSCR
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: dcd290ed-ae69-435e-89db-82a64cb1291a
                stepCounter: ae8117b4-5e98-4a14-b772-0a8e942cac9b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: db0db07e-8107-4cc3-ab5c-bd21beef72c6
          stepCounter: f50f2841-f884-4178-aa77-4064b5e1398a
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: PCADDED_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: da009c5d-6635-4a15-b366-d2493ac08666
                stepCounter: ae8117b4-5e98-4a14-b772-0a8e942cac9b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: aefb1923-80d3-45e3-a148-c40936ee944e
          stepCounter: f50f2841-f884-4178-aa77-4064b5e1398a
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: LAST_MODIFIED_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4e04db28-0ad4-4c07-b3f4-9bcab2b63184
                stepCounter: ae8117b4-5e98-4a14-b772-0a8e942cac9b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 899c75a2-aeb6-4f51-a818-0bfaf0a10d65
          stepCounter: f50f2841-f884-4178-aa77-4064b5e1398a
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: Record source
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e84ef218-7c5e-4992-bcbd-5a04816004fe
                stepCounter: ae8117b4-5e98-4a14-b772-0a8e942cac9b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b3854d67-8e9d-4ef4-9f40-c1292da6ccbd
          stepCounter: f50f2841-f884-4178-aa77-4064b5e1398a
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was loaded
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 289d2800-dd87-4b19-80d7-9578375352f9
                stepCounter: ae8117b4-5e98-4a14-b772-0a8e942cac9b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dbb2978d-fedc-4bfb-879d-e6b97f66d166
          stepCounter: f50f2841-f884-4178-aa77-4064b5e1398a
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: To track delted records from source system
        name: TO_BE_DELETED
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: cecf0066-2e3b-4095-85f8-dfcaab7fb161
                stepCounter: ae8117b4-5e98-4a14-b772-0a8e942cac9b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6098f775-d752-49e9-b499-b38f66720fe3
          stepCounter: f50f2841-f884-4178-aa77-4064b5e1398a
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7e9f0500-a58e-4f99-b6af-aa6e265fe283
          stepCounter: f50f2841-f884-4178-aa77-4064b5e1398a
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a0f9c8e2-2309-477f-8d64-f3a6bf782d57
          stepCounter: f50f2841-f884-4178-aa77-4064b5e1398a
        config: {}
        dataType: VARCHAR(3)
        defaultValue: ""
        description: ""
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 475aa315-730a-426c-8ff3-13f36043299f
          stepCounter: f50f2841-f884-4178-aa77-4064b5e1398a
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isSystemVersion: true
        name: DSS_VERSION
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5fbadd48-b7b1-4085-a4ca-a37e6c8b020a
          stepCounter: f50f2841-f884-4178-aa77-4064b5e1398a
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 03b912ed-1bd5-41c1-b492-05ce97c0162d
          stepCounter: f50f2841-f884-4178-aa77-4064b5e1398a
        config: {}
        dataType: TIMESTAMP_NTZ(9)
        defaultValue: ""
        description: ""
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LD_DC64_POLICYDETAILSETTINGS: ae8117b4-5e98-4a14-b772-0a8e942cac9b
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: DATA_LAKE
            nodeName: LD_DC64_POLICYDETAILSETTINGS
        join:
          joinCondition: FROM {{ ref('DATA_LAKE','LD_DC64_POLICYDETAILSETTINGS') }} ld_dc64_policydetailsettings
        name: DL_DC64_POLICYDETAILSETTINGS
        noLinkRefs: []
  name: DL_DC64_POLICYDETAILSETTINGS
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
