fileVersion: 1
id: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
name: DL_CPS_ONDEMAND_SETTINGS_OVERRIDE
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: DATA_LAKE
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4fa29200-ca21-489d-863f-69228d83a063
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: ID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6ce3e498-c758-400a-9371-4544f6393300
                stepCounter: 02bd4c8f-e832-4da1-95bb-14fc2f6d1967
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f36d4354-0eed-4d28-9224-2493f9afb05a
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: WINDOWSAGENTID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 7db05cff-3e78-4be9-aa39-7aad9d473ab8
                stepCounter: 02bd4c8f-e832-4da1-95bb-14fc2f6d1967
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 98efff47-789a-42d0-8540-8e1a83392032
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: ISAUDIORECORDING
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 505f5dfc-8198-4390-815d-6103e769c08f
                stepCounter: 02bd4c8f-e832-4da1-95bb-14fc2f6d1967
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 74f68cf7-f7ec-4f73-ab74-2193073dc513
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: ISSCREENRECORDING
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 50aea0be-c73e-48e4-86be-39944f4b681e
                stepCounter: 02bd4c8f-e832-4da1-95bb-14fc2f6d1967
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 88ac7c63-2862-4932-b112-c5bfdbe4bfae
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: USERTYPE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ed86985a-9829-4553-a2ec-d824ad141357
                stepCounter: 02bd4c8f-e832-4da1-95bb-14fc2f6d1967
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 13bc164e-07ab-4a69-aead-bffaae981200
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: ISACTIVE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 749c4b74-4198-4082-b035-e730a7740086
                stepCounter: 02bd4c8f-e832-4da1-95bb-14fc2f6d1967
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: eee55bc6-ebc5-4fd4-8836-e6dcc145eaf6
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: EDITEDDATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 22bf1567-0417-4fe0-9cf8-5ece54dde598
                stepCounter: 02bd4c8f-e832-4da1-95bb-14fc2f6d1967
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5581f453-fa03-4133-9379-c4348c6bf763
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: Record source
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 259e4b64-f363-47ad-bd21-54709388610e
                stepCounter: 02bd4c8f-e832-4da1-95bb-14fc2f6d1967
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6b231faa-77d1-405e-99a1-06bb418bf3c1
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was loaded
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f7ffcbcc-1b82-4616-b31f-93c01b174b6b
                stepCounter: 02bd4c8f-e832-4da1-95bb-14fc2f6d1967
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ce6b296d-d295-4856-b886-961cc32f469c
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: To track delted records from source system
        name: TO_BE_DELETED
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 97fd5edd-bba2-4bc5-981a-8c35bcdaa7b6
                stepCounter: 02bd4c8f-e832-4da1-95bb-14fc2f6d1967
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 985a88ca-2ec7-4bdc-b0c8-984e4a5b0e36
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 23ca6d2c-0c1c-4e2a-ad98-4e5b15b62718
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e564c20a-8182-4801-acb5-43dcd7723c8b
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: VARCHAR(3)
        defaultValue: ""
        description: ""
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7abceecb-04dd-4288-94b0-d92183645d27
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isSystemVersion: true
        name: DSS_VERSION
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 18371912-7de5-45b4-8fbe-5d71a38127ad
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 41425ed0-37e6-409e-9112-fc905ef53c0c
          stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        config: {}
        dataType: TIMESTAMP_NTZ(9)
        defaultValue: ""
        description: ""
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LD_CPS_ONDEMAND_SETTINGS_OVERRIDE: 02bd4c8f-e832-4da1-95bb-14fc2f6d1967
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: DATA_LAKE
            nodeName: LD_CPS_ONDEMAND_SETTINGS_OVERRIDE
        join:
          joinCondition: FROM {{ ref('DATA_LAKE','LD_CPS_ONDEMAND_SETTINGS_OVERRIDE') }} ld_cps_ondemand_settings_override
        name: DL_CPS_ONDEMAND_SETTINGS_OVERRIDE
        noLinkRefs: []
  name: DL_CPS_ONDEMAND_SETTINGS_OVERRIDE
  overrideSQL: false
  schema: ""
  sqlType: "38"
  type: sql
  version: 1
type: Node
