fileVersion: 1
id: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
name: V_DL_CPS_ONDEMAND_SETTINGS_SITE_CURRENT
operation:
  config:
    insertStrategy: UNION
    selectDistinct: false
  customOverride: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: DATA_LAKE
  materializationType: view
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f2ca007b-1932-4bad-bf61-e9e08b6afd3d
          stepCounter: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: ID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 778be195-09da-4b31-b606-b2b8bd6ef65d
                stepCounter: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9a23cf97-0874-4b82-84fd-2fe45c70e1a3
          stepCounter: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: KEYDESCRIPTION
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e16a1fd8-e0c4-474f-a7d7-ca11caeb8a7d
                stepCounter: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 97f8f9e3-0375-462b-95b8-76283b5d9f33
          stepCounter: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: VALUE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 78f968eb-5f9c-4c2e-9d2a-f5820725b64a
                stepCounter: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4d0bbb54-8a5c-4a45-917c-2f3f052ea02e
          stepCounter: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ISACTIVE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b4367d4d-138e-46f3-ab3f-5ead4d53ad48
                stepCounter: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: baca2ba9-7e22-4317-9212-268a78d5c94c
          stepCounter: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
        config: {}
        dataType: TIMESTAMP(7)
        defaultValue: ""
        description: ""
        name: INPUTDATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8d895752-918b-42c5-8290-35677dac877a
                stepCounter: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1d6e8160-f4fa-466e-94c0-5e6338fe2a50
          stepCounter: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: NOTE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e00080ae-f8ef-400a-b21c-f6ffa5c85fcc
                stepCounter: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d0f4ed60-2ce5-434d-b9c8-91914a430ef3
          stepCounter: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: Record source
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: bdf47a4d-5cdc-4f4f-84c3-3c66ca563a05
                stepCounter: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 710717ec-934b-4ef6-be38-6a2a4327ea49
          stepCounter: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was loaded
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b8bb1979-ae43-4eda-bb51-d7456976085e
                stepCounter: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fbb49070-f6e5-4bed-82ac-208c074fc315
          stepCounter: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: To track delted records from source system
        name: TO_BE_DELETED
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e18f6811-076e-4934-bff9-03fff49d4679
                stepCounter: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3c58cdcb-d782-411e-a559-3aaba33d373a
          stepCounter: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 303100ad-9f7b-4c30-a5ed-821c94ff82e7
                stepCounter: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b25e776f-acf6-4740-a898-00262f82aac8
          stepCounter: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c080fac5-70fd-45b0-83f3-8ff8f1b26448
                stepCounter: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5ee4e91d-eda5-4ba5-9bec-7162ba216a05
          stepCounter: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
        config: {}
        dataType: VARCHAR(3)
        defaultValue: ""
        description: ""
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 7b339d8c-108c-4d86-9cc3-44bfae6e8e4a
                stepCounter: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1f8e1242-fb29-4f84-93ab-a7a1e679eb16
          stepCounter: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isSystemVersion: true
        name: DSS_VERSION
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 256e134d-ffeb-426b-a960-ad688cb45fdf
                stepCounter: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ba4c4aa6-507a-4967-9cc8-6411b3832ba5
          stepCounter: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: dac5edfe-a489-4c10-a628-83ebe455f0f2
                stepCounter: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d2b21604-b7bc-413a-aea2-997b8a484dac
          stepCounter: 36c4d1fe-b2e6-4769-bf72-076cab1b6272
        config: {}
        dataType: TIMESTAMP_NTZ(9)
        defaultValue: ""
        description: ""
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 9d3fa17b-126b-460e-9976-6d24eef339f3
                stepCounter: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          DL_CPS_ONDEMAND_SETTINGS_SITE: 8e2b46a9-cf59-4a4a-8ecc-42f958e2ac5d
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: DATA_LAKE
            nodeName: DL_CPS_ONDEMAND_SETTINGS_SITE
        join:
          joinCondition: FROM {{ ref('DATA_LAKE','DL_CPS_ONDEMAND_SETTINGS_SITE') }} dl_cps_ondemand_settings_site
        name: V_DL_CPS_ONDEMAND_SETTINGS_SITE_CURRENT
        noLinkRefs: []
  name: V_DL_CPS_ONDEMAND_SETTINGS_SITE_CURRENT
  overrideSQL: false
  schema: ""
  sqlType: View
  type: sql
  version: 1
type: Node
