fileVersion: 1
id: 852dd38f-9582-4f98-93da-d6dcefe31090
name: DL_PCCE_APPLICATION_GATEWAY_CONNECTI
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: DATA_LAKE
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c4116366-dcd7-46a6-bd5e-7661abdacccd
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: APPLICATIONGATEWAYID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 50e7ad4d-a491-4ea8-823c-9f3c38481bb5
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 61f130d8-24bd-450d-a7a1-a4d8e1a67292
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: SIDE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: eb7e3415-8d8e-4d98-b51b-633acba2d9cc
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1a0cf4e6-6df5-4bf7-a21c-d823aac1da26
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: ADDRESS
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 188cc234-9f69-4d12-b06d-c00b4be0f2fe
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7da44faf-bea4-4308-8ed3-e1f1256b4718
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: PROTOCOL
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 999c77c3-d077-4d83-a70d-331de5cb918c
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e716a3a9-ae47-4a9b-ae22-4eb20742ea55
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: CONNECTINFO
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0131f873-0379-4393-a96a-8e354bd771ff
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1b721040-45d2-4642-9d95-464fab63804f
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: DESCRIPTION
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b9fac7d0-dd92-4a6d-ba9e-5987e90e24eb
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 41592073-d958-43ef-91a8-b625484a3980
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: INSERVICE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 44ee94e0-5d95-420f-a747-20cd9bb0afb9
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 72175f5d-204d-401f-adbd-a258158c8e91
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: ERRORTHRESHOLD
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: aa7dd598-9544-475f-a58c-1eb3ddee133f
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fd607a29-c9d2-4771-8cbb-c7a76f588cbc
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: REQUESTTIMEOUT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1aa0936d-d425-4d26-a0c8-353fef4440af
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9e396728-b771-4c89-8c71-fd50580012e4
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: ABANDONTIMEOUT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 55ba99b3-a333-4865-a47d-a9ae0584035e
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6c7c717d-dcef-4dda-bb1c-377b22c378b8
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: SESSIONRETRY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 9fd500e3-3c25-4ad5-be7a-3120f7e35905
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 06b65760-54d1-41db-8c33-9b8869146a82
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: SESSIONRETRYLIMIT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 44fd7ef4-75fe-4f79-8f2a-3c926f8ce4d1
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 08adea9a-7c5f-445b-9a13-fbc9067cd884
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: OPENTIMEOUT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 27757000-6317-4c36-945c-058fe06a8b8e
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 16cd399e-352e-46c4-b8a3-a4e51253eb6c
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: HEARTBEATTIMEOUT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 369c3617-a7fe-4115-9f82-072487990268
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 604bd43b-4e5d-42b0-8ef9-c1fe4355c680
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: HEARTBEATLIMIT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2695b8e4-a9d6-4954-a884-e075f3f024f1
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b94527e7-5b72-4b1f-8e24-4d691341436c
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: HEARTBEATRETRY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: df06325c-f789-4b8f-b86b-0f463f6aa47b
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c32343cc-1980-421c-aa0b-0a0fdef2c3bf
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: HEARTBEATINTERVAL
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ba6d8bee-308c-4a14-89fc-886874af8152
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 292026a7-f5b4-49c4-815f-5d933bb76f48
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: COMMAND
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6529a8e5-ef46-49e0-aa09-736053105264
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8c84096d-2108-439a-9820-b8604292f488
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: COMMANDPARAM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8c65d05c-6594-4c05-baca-066b25f0c55d
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ec141cf4-3e28-4477-9f4b-75889423a5bd
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: LINKTESTTHRESHOLD
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c5444d28-28e4-41aa-9849-e4046e221bf2
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 725d31e3-aaf0-4bf2-b2ba-956c09e37b6f
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: LATETIMEOUT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: bc201773-219a-4a22-84ed-c864789a0b34
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a90bf6e3-7fcc-4f6c-9253-be02f981cb14
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: Record source
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d8359860-2ec2-47b3-9ea1-5e701d330ed9
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ec75edf8-fb1b-49e8-a223-d70e94ef7304
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was loaded
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ba967254-424a-4550-909d-b461d1fce557
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2f47e662-9a1b-48f9-af53-d6dd54f9866b
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: To track delted records from source system
        name: TO_BE_DELETED
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 7d481243-d8ae-4850-b2f4-3ab725d1e8c9
                stepCounter: f884ef29-b595-4cf9-8be3-d85383fc1770
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d3198a54-30fd-4b8c-9ece-7b288bc73c40
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a0e6fb34-5f52-411e-a293-3f7c9e881cc6
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 06e43405-9b77-43e9-8fcf-3a824728ccc6
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: VARCHAR(3)
        defaultValue: ""
        description: ""
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 77050c74-5320-43b9-b3bc-df0520532e05
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isSystemVersion: true
        name: DSS_VERSION
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e29d39d2-919c-4f01-b954-949b427dd81c
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 80573e02-5956-4acf-a258-f3f4ffac6538
          stepCounter: 852dd38f-9582-4f98-93da-d6dcefe31090
        config: {}
        dataType: TIMESTAMP_NTZ(9)
        defaultValue: ""
        description: ""
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LD_PCCE_APPLICATION_GATEWAY_CONNECTI: f884ef29-b595-4cf9-8be3-d85383fc1770
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: DATA_LAKE
            nodeName: LD_PCCE_APPLICATION_GATEWAY_CONNECTI
        join:
          joinCondition: FROM {{ ref('DATA_LAKE','LD_PCCE_APPLICATION_GATEWAY_CONNECTI') }} ld_pcce_application_gateway_connecti
        name: DL_PCCE_APPLICATION_GATEWAY_CONNECTI
        noLinkRefs: []
  name: DL_PCCE_APPLICATION_GATEWAY_CONNECTI
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
