fileVersion: 1
id: 03d06af7-3824-4959-bceb-d68fd48434eb
name: DL_PCCE_APPLICATION_PATH_REAL_TIME
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: DATA_LAKE
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9852aa72-e1b5-4c8e-bd81-e28e82234da5
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: APPLICATIONPATHID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1e477029-e8c5-419e-8daa-20b270ef0944
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ebc499d4-0c3a-4769-b3f6-9da7e9b48831
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: DATETIME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1d749913-f7fc-4047-b634-5d6143dcb2a4
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 23b5b4f4-589b-4cbc-b069-8920e7b0c041
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: ONLINEDATETIME
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 09f50d31-1937-4bef-9631-4e2df76c82d1
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 606a92e6-9467-4d24-a642-7cdfd1d4938d
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: ONLINE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 26785392-b260-4a57-9f52-72d6cd80a5e7
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8a9482f5-56d0-44a5-a5b3-c99b05b3f14a
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: TEXT1
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 05037a07-7030-4c69-a231-6a22f6e5820c
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f402a684-362b-49a3-94c2-017c3b879c97
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: TEXT2
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 056606c9-fc06-452b-93d5-11579314992a
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 52395efe-f730-4686-a761-c317ab809582
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: TEXT3
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: bb405e32-52e6-4dd4-adc7-cb367a3f1e66
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a211d744-b2f0-4f4e-a827-25acb62159af
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: TEXT4
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ff86f1dc-f31b-489c-9cfc-41842d1d0073
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5d90dcf1-e18e-4080-a946-32a7eb0b4f3c
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: TEXT5
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 76bdeb26-0533-4876-9567-7baf7c78e791
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e552cf5d-71dd-4346-8476-cfa7ff76a414
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: TEXT6
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 205d1093-994a-496d-81c8-361ab7a3073b
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4146fbc5-7a1f-47ca-8623-05e656254cd4
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: TEXT7
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6b81c0a1-7dd2-40e9-a636-bbccdc1019ff
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 89ea7ed2-ba8a-4666-9ec7-815dc6907e95
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: TEXT8
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 950120c6-8cb5-4209-bbb4-00c167cb9649
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 20b6dbc5-2add-4ebf-a6cf-64c9a238d4c5
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: TEXT9
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: fb1cf9aa-1f2b-4584-92d2-d2b18f7aea10
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8de7ecaf-45f7-4637-8270-9606420ee4c7
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: ""
        isChangeTracking: true
        name: TEXT10
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b294a348-d939-473a-967d-cee58ebc56c1
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cd7795ea-3945-4cf9-bd38-3770cf3eb640
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: Record source
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f8508978-de6e-4615-a28a-f2470f3186e2
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3ee271f7-45a3-479a-9b03-1deac6697099
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was loaded
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f818550c-9bc2-4049-bcb3-4339d024daad
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d7df153f-b2d5-4b16-a10c-4b53494a343b
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: To track delted records from source system
        name: TO_BE_DELETED
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: eb1aa332-ae4e-4a0d-89aa-7ec5b737c810
                stepCounter: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 00ed0983-956f-473d-a57a-8dd975f2547f
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c21037bf-52c6-4528-adb4-0bf5fdd7aec0
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7d6920d4-4c25-4cdd-b523-7fabd6d6b92e
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: VARCHAR(3)
        defaultValue: ""
        description: ""
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6dae3a2f-cdd9-48b6-a18c-4b26ef1a6422
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isSystemVersion: true
        name: DSS_VERSION
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4f4e00ce-960f-4e04-b35a-15a8fe4e909c
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b3724d39-541d-4308-a317-8b44d45f8ec6
          stepCounter: 03d06af7-3824-4959-bceb-d68fd48434eb
        config: {}
        dataType: TIMESTAMP_NTZ(9)
        defaultValue: ""
        description: ""
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LD_PCCE_APPLICATION_PATH_REAL_TIME: 7fd33c72-14c8-4f01-9af5-f87ed4e3050d
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: DATA_LAKE
            nodeName: LD_PCCE_APPLICATION_PATH_REAL_TIME
        join:
          joinCondition: FROM {{ ref('DATA_LAKE','LD_PCCE_APPLICATION_PATH_REAL_TIME') }} ld_pcce_application_path_real_time
        name: DL_PCCE_APPLICATION_PATH_REAL_TIME
        noLinkRefs: []
  name: DL_PCCE_APPLICATION_PATH_REAL_TIME
  overrideSQL: false
  schema: ""
  sqlType: '38'
  type: sql
  version: 1
type: Node
