fileVersion: 1
id: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
name: V_DL_DC49_POLICYDETAILSETTINGSVERSION_CURRENT
operation:
  config:
    insertStrategy: UNION
    selectDistinct: false
  customOverride: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: DATA_LAKE
  materializationType: view
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9c913a2b-4d46-43f8-9dd6-851b554bf2b0
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: POLICYDETAILSETTINGSVERSION_ID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 57b3fc64-b5eb-464d-a145-5756f34195c1
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b15aca66-5dfc-4a80-b9a2-97d2b3d198cb
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: POLICYDETAILSETTINGS_ID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f2c448cd-c036-4e49-a7f7-a6915d771728
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 90b9c760-f905-4c5b-8054-9374fd216f9b
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: COMPANYSTATELOB_ID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5c0d7501-4e58-427f-8c9e-a61d9edee392
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b6a4789e-93a9-4aef-93e2-67671b74fa05
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: VALUE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b4e08b24-e001-4976-b8e0-be9bbb5aacbb
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 00b436cb-5a30-4803-bd1c-7771eab42828
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        name: NEW_EFFECTIVE_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2df5ecc0-0e73-4f12-a3b9-48ef79d84d58
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1cd25f7c-eac3-4e75-adec-6cfc6c15317f
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        name: NEW_EXPIRATION_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 02757a32-9fb5-4871-9c13-53722498f9fd
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f2791ad7-9507-4d0e-accb-af6645e3fbae
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        name: REN_EFFECTIVE_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ee0532b5-7f00-4ff9-8ae2-c780fe3dc4e0
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 37a8d205-9ddc-453f-b6fc-74cc0b996f1c
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        name: REN_EXPIRATION_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 790c7a93-2c7d-4608-8f45-6be6acafced7
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d390986b-0be7-4045-9557-417e34a58661
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        name: PCADDED_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a2ee456d-ddad-40c4-93c3-c4f108d59c8a
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 75e176b2-30ad-4f92-b8ee-90c6865f52c3
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 68df3b4c-cfe2-4183-876e-81011316d8a4
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cf206bcb-d139-4efc-a63e-85b75b3c4d28
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: NUMBER(19,4)
        defaultValue: ""
        description: ""
        name: MIN_RANGE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 64982841-54ce-432f-aad6-73f2dd8870ea
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 73535023-b7fc-43b8-96e2-293a2ef24868
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: NUMBER(19,4)
        defaultValue: ""
        description: ""
        name: MAX_RANGE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 7e3bd48c-d6d5-4541-8825-b49832678cf4
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 9b29141c-75c3-437b-a02b-3108297d179b
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: Record source
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d53ede40-9248-4c69-af12-307c7d5d4fb4
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 473bf3ba-f163-4bb3-8492-fe758eb8e589
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was loaded
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4851fab7-d0f4-4ccb-9063-f3e3e2ed3bbb
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: efeed0e4-37e5-4f08-97e4-134c365a7a62
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: To track delted records from source system
        name: TO_BE_DELETED
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b6701185-f948-437c-b082-69b09126df31
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e8290ce1-7ede-40a1-906f-25182fa2423d
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a3951db5-2ce8-4009-a788-908f00118012
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e285e0e3-54b0-46ac-831c-4e47725589ca
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c63bf819-559e-43be-9a63-d648239363a7
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c0c2c5c8-a79b-46c2-a913-74702c499551
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: VARCHAR(3)
        defaultValue: ""
        description: ""
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2ea2f97c-7ce1-4680-98b8-eadb33b7cfc9
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8aa8cf7c-37e0-40f3-8acd-08ed254c2860
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isSystemVersion: true
        name: DSS_VERSION
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: cae4d23d-998e-4c59-b30f-a2c882f3b62e
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 15f8534b-eb98-4964-a6e8-3efe63c4dc23
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 34e26371-e41c-4fe2-ab29-c9d956d2e050
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7da52fc5-0771-48b8-a016-ebdb28980288
          stepCounter: 5e9cf4f4-bc0e-4026-95ed-f29715acf448
        config: {}
        dataType: TIMESTAMP_NTZ(9)
        defaultValue: ""
        description: ""
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5a69e208-e836-4fd2-9e7b-318e1408b9ea
                stepCounter: 0833357d-ff39-448c-b249-8067fe241f51
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          DL_DC49_POLICYDETAILSETTINGSVERSION: 0833357d-ff39-448c-b249-8067fe241f51
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: DATA_LAKE
            nodeName: DL_DC49_POLICYDETAILSETTINGSVERSION
        join:
          joinCondition: FROM {{ ref('DATA_LAKE','DL_DC49_POLICYDETAILSETTINGSVERSION') }} dl_dc49_policydetailsettingsversion
        name: V_DL_DC49_POLICYDETAILSETTINGSVERSION_CURRENT
        noLinkRefs: []
  name: V_DL_DC49_POLICYDETAILSETTINGSVERSION_CURRENT
  overrideSQL: false
  schema: ""
  sqlType: View
  type: sql
  version: 1
type: Node
