fileVersion: 1
id: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
name: V_DL_CPS_ONDEMAND_SETTINGS_OVERRIDE_CURRENT
operation:
  config:
    insertStrategy: UNION
    selectDistinct: false
  customOverride: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: DATA_LAKE
  materializationType: view
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b35d2f5c-d14b-401b-abab-3a1896a40204
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: NUMBER
        defaultValue: ""
        description: ""
        name: ID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4fa29200-ca21-489d-863f-69228d83a063
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 67af28d7-149c-4836-b616-bde371049a28
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: WINDOWSAGENTID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f36d4354-0eed-4d28-9224-2493f9afb05a
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0d574689-b1aa-4a45-bd86-efe130122ea0
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ISAUDIORECORDING
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 98efff47-789a-42d0-8540-8e1a83392032
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fb34950a-d842-4b69-9263-a772719a8ba8
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ISSCREENRECORDING
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 74f68cf7-f7ec-4f73-ab74-2193073dc513
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 639bc21b-0edc-4618-84dd-5e7bd73b8551
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: USERTYPE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 88ac7c63-2862-4932-b112-c5bfdbe4bfae
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d28bafd6-5d66-46c7-a61b-2d45a3fa4473
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: VARCHAR(20)
        defaultValue: ""
        description: ""
        name: ISACTIVE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 13bc164e-07ab-4a69-aead-bffaae981200
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3eaac955-8db8-4d35-90b4-3e958565eed4
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        name: EDITEDDATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: eee55bc6-ebc5-4fd4-8836-e6dcc145eaf6
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ef48af6b-0275-499d-a93d-0ef4ddcbf5bb
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: Record source
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5581f453-fa03-4133-9379-c4348c6bf763
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ed9dd7e5-cd58-493d-afa9-182a3d4b5237
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was loaded
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6b231faa-77d1-405e-99a1-06bb418bf3c1
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e1942581-108b-4cef-81f5-2a9e933c6398
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: To track delted records from source system
        name: TO_BE_DELETED
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ce6b296d-d295-4856-b886-961cc32f469c
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bc6a3e4f-f688-447a-80d9-1305d672fd70
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 985a88ca-2ec7-4bdc-b0c8-984e4a5b0e36
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e546507a-5a68-4d7a-9f0f-311622fbd62a
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 23ca6d2c-0c1c-4e2a-ad98-4e5b15b62718
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 68374b6e-cb33-4eed-8db9-2d4e4de6d4af
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: VARCHAR(3)
        defaultValue: ""
        description: ""
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e564c20a-8182-4801-acb5-43dcd7723c8b
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 852a0546-07fc-449c-a121-a1b165239de1
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isSystemVersion: true
        name: DSS_VERSION
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 7abceecb-04dd-4288-94b0-d92183645d27
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 44df1dee-b637-4187-8684-6dcff8d70002
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 18371912-7de5-45b4-8fbe-5d71a38127ad
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: eff36000-ccc7-4936-b3b9-dc30cbe565f9
          stepCounter: 6fd5f732-f813-49ab-acf7-c3aafc69af0d
        config: {}
        dataType: TIMESTAMP_NTZ(9)
        defaultValue: ""
        description: ""
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 41425ed0-37e6-409e-9112-fc905ef53c0c
                stepCounter: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          DL_CPS_ONDEMAND_SETTINGS_OVERRIDE: 9cbfa3ba-3e5f-4058-a903-ac84786d1998
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: DATA_LAKE
            nodeName: DL_CPS_ONDEMAND_SETTINGS_OVERRIDE
        join:
          joinCondition: FROM {{ ref('DATA_LAKE','DL_CPS_ONDEMAND_SETTINGS_OVERRIDE') }} dl_cps_ondemand_settings_override
        name: V_DL_CPS_ONDEMAND_SETTINGS_OVERRIDE_CURRENT
        noLinkRefs: []
  name: V_DL_CPS_ONDEMAND_SETTINGS_OVERRIDE_CURRENT
  overrideSQL: false
  schema: ""
  sqlType: View
  type: sql
  version: 1
type: Node
