fileVersion: 1
id: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
name: V_BLT_POL_APPLICATION_SUBMITTED_ADDRESS_DETAILS
operation:
  config:
    insertStrategy: UNION
    selectDistinct: false
  customOverride: false
  database: ""
  deployEnabled: false
  description: ""
  isMultisource: false
  locationName: DATA_LAKE
  materializationType: view
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 72463ba9-b299-4191-b4a9-6efd93086d26
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: DECIMAL(38,0)
        defaultValue: ""
        description: ""
        name: SUBMITTED_ADDRESS_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: fef6ddbe-f9e7-496b-8256-325000f4f4e6
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: DECIMAL(38,0)
        defaultValue: ""
        description: ""
        name: CUSTOMER_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2c9e2a4f-ad50-4dba-a232-31d699057c58
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: SUB_CUSTOMER_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: dfb30fbe-94a7-424c-8902-2dfb7166e41c
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: SUB_CUSTOMER_GROUP_NM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 904f9cea-cce8-46a7-88ea-21bdeed652f6
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: SUBMITTED_ADDRESS_NUM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7c441360-3701-451d-8e44-8a8434d06820
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: DECIMAL(38,0)
        defaultValue: ""
        description: ""
        name: APPLICATION_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b64977d3-db69-4ca3-8b4d-2fec7ee55540
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: APPLICATION_NUM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 302305d7-2e96-4f47-94ef-e81ce62c7a63
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: PLATFORM_APPLICATION_NUM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cf8ab755-d923-494b-983f-2287a08c0f58
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: DECIMAL(38,0)
        defaultValue: ""
        description: ""
        name: APPLICATION_SUBMITTED_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: aef9965a-9d69-4f5f-9b93-443050c4494a
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: APPLICATION_SUBMITTED_NUM
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 84f2aa3d-750b-4c5a-8aaf-0635176ab612
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: ADDRESS_TYPE_CD
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 304e2339-8f97-4275-8c58-482cd2f7168d
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: ADDRESS_TYPE_DESC
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 000f0bee-51c9-4976-990e-aef6bfdeeeca
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: SUBMITTED_ADDRESS_LINE_1
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a3628eee-440d-4a0a-bea2-611af64e3b1f
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: SUBMITTED_ADDRESS_LINE_2
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 2c8937c3-9de4-4515-8a15-5c4a8d0eee15
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: APPLICATION_CITY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5cb5f8c6-25a3-4eaf-acf2-a169baf8d517
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: APPLICATION_STATE_CD
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 64a3c1f1-c85a-42b5-89d4-a54e56f6f068
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: APPLICATION_STATE_DESC
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 363160a2-ee7f-41ac-a514-bb239d5003d9
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: APPLICATION_ZIP
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 368e99bf-f583-4555-83a1-adc2553630da
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: APPLICATION_COUNTY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f95f1d3c-1149-4092-b6c4-086a14899d41
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: APPLICATION_COUNTRY_CD
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: aff3e524-a9bc-470b-b8d4-e7eff8652ad2
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: APPLICATION_COUNTRY_DESC
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b88af2c2-9136-4a3a-9a59-3bfc8f7d8fa5
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: ACTIVE_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cccdaf8e-f513-46a7-9c9a-b8c17a1c23a7
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: AUDIT_SRC_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7dcc9b9b-b62b-4100-824a-39c6e1767231
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: AUDIT_SYS_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b335b735-3691-483a-8370-5ffaeeca582c
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: DECIMAL(38,0)
        defaultValue: ""
        description: ""
        name: AUDIT_BATCH_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7a4b3c96-7fb4-4c80-a642-05992e3b34f4
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: DECIMAL(38,0)
        defaultValue: ""
        description: ""
        name: AUDIT_SUB_BATCH_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f8bbb533-6521-4b03-854c-9ef3f9215cf6
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: AUDIT_IU_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: af84ad57-9006-4fdc-bc81-7854165f07b6
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: LAST_UPDATE_DT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f56163c8-c440-4265-ae0c-3ad24ba56af0
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: DECIMAL(38,0)
        defaultValue: ""
        description: ""
        name: LAST_UPDATE_USER_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 47998335-c29b-44f5-b4b7-6ab17aa6825f
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: DECIMAL(38,0)
        defaultValue: ""
        description: ""
        name: AUDIT_TABLE_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 41698770-d425-45be-801e-2debb98a52a2
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: AUDIT_STORAGE_LEVEL
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8b88f6ec-9d92-49ba-ab1d-142ee89b8009
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: _CHANGE_TYPE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7dc09d42-171d-43ef-a66f-561d47d4858d
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: FILENAME
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: f07065d4-429f-4920-9f86-67d5868f503a
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        name: RUNDATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: "0"
                stepCounter: "0"
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 3ca8339d-3e1c-4e0c-a880-38d80298daf8
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: TGT_VARCHAR(255)
        defaultValue: ""
        description: Record source
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: "'SRC_EDWCommon_blt.BOLT.POL_APPLICATION_SUBMITTED_ADDRESS_DETAILS'"
      - appliedColumnTests: {}
        columnReference:
          columnCounter: b87f0a9a-fc7e-4609-af02-3456f090aa49
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: TGT_DATETIME
        defaultValue: ""
        description: Date and time the row was loaded
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP_NTZ)
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bbcc59b3-53a7-4f2d-b690-d587798caebf
          stepCounter: 1af3d1d5-bbea-474a-8716-9b130d97b5b5
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: To track delted records from source system
        name: TO_BE_DELETED
        nullable: true
        sourceColumnReferences:
          - columnReferences: []
            transform: "'N'"
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases: {}
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: UNKNOWN
            nodeName: POL_APPLICATION_SUBMITTED_ADDRESS_DETAILS
        join:
          joinCondition: FROM EDW_COMMON.BOLT.POL_APPLICATION_SUBMITTED_ADDRESS_DETAILS POL_APPLICATION_SUBMITTED_ADDRESS_DETAILS
        name: V_BLT_POL_APPLICATION_SUBMITTED_ADDRESS_DETAILS
        noLinkRefs: []
  name: V_BLT_POL_APPLICATION_SUBMITTED_ADDRESS_DETAILS
  overrideSQL: false
  schema: ""
  sqlType: View
  type: sql
  version: 1
type: Node
