fileVersion: 1
id: 603404ec-df0e-46db-a2a5-81b34c4cb8a0
name: V_DLBV_DC81_DETAILSETTINGS_CURRENT
operation:
  config:
    insertStrategy: UNION
    selectDistinct: false
  customOverride: false
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: STAGE
  materializationType: view
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a02c89d7-e9d3-4844-a63c-bb43d938242b
          stepCounter: 603404ec-df0e-46db-a2a5-81b34c4cb8a0
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        name: DETAILSETTINGS_ID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d5a8d2ef-abcc-4cb5-9d84-3ee23cbd1b7c
                stepCounter: 103c2e43-fbba-4968-8290-2b2cc5127f13
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0af92b15-8e98-4c40-9ffb-0c6637ae070e
          stepCounter: 603404ec-df0e-46db-a2a5-81b34c4cb8a0
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: ""
        name: DSCR
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: fa9e7046-42b3-4c77-b963-99289bc4c00e
                stepCounter: 103c2e43-fbba-4968-8290-2b2cc5127f13
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 8b3011b4-87ee-4bbc-82c5-c47a8dae4c90
          stepCounter: 603404ec-df0e-46db-a2a5-81b34c4cb8a0
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        name: PCADDED_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f019a156-3a33-4653-a1cb-610d1c5c63d0
                stepCounter: 103c2e43-fbba-4968-8290-2b2cc5127f13
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cb0c0421-dfac-4783-aa86-e0bb638c1d22
          stepCounter: 603404ec-df0e-46db-a2a5-81b34c4cb8a0
        config: {}
        dataType: TIMESTAMP(3)
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 596aaa3f-6872-4497-849c-fb98083facba
                stepCounter: 103c2e43-fbba-4968-8290-2b2cc5127f13
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6667a167-9e6b-40df-af2c-6c536ec8d52d
          stepCounter: 603404ec-df0e-46db-a2a5-81b34c4cb8a0
        config: {}
        dataType: VARCHAR(255)
        defaultValue: ""
        description: Record source
        name: DSS_RECORD_SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4f81bb2b-cdbe-4f45-9e98-1ea607514003
                stepCounter: 103c2e43-fbba-4968-8290-2b2cc5127f13
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 4b6ce703-f1c7-4fb6-bc5a-d56202cad29d
          stepCounter: 603404ec-df0e-46db-a2a5-81b34c4cb8a0
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was loaded
        name: DSS_LOAD_DATE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0b7c960c-0f51-4de7-97aa-1262a6a5f940
                stepCounter: 103c2e43-fbba-4968-8290-2b2cc5127f13
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7da5677e-5ba3-4b15-b209-5a842bc691a6
          stepCounter: 603404ec-df0e-46db-a2a5-81b34c4cb8a0
        config: {}
        dataType: CHAR(1)
        defaultValue: ""
        description: To track delted records from source system
        name: TO_BE_DELETED
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 057fefec-8cef-448f-80c2-ab3694978033
                stepCounter: 103c2e43-fbba-4968-8290-2b2cc5127f13
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: cef82f1a-511b-4364-bae7-406035ef5657
          stepCounter: 603404ec-df0e-46db-a2a5-81b34c4cb8a0
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemStartDate: true
        name: DSS_START_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d98c63f9-61e4-4dea-a869-d4a99df245f4
                stepCounter: 103c2e43-fbba-4968-8290-2b2cc5127f13
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: bec3c8d2-1966-4b80-8715-43f48e7317d0
          stepCounter: 603404ec-df0e-46db-a2a5-81b34c4cb8a0
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemEndDate: true
        name: DSS_END_DATE
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 24650b78-e19f-4ee6-98e3-559f390a5954
                stepCounter: 103c2e43-fbba-4968-8290-2b2cc5127f13
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 00890798-63e1-4a4b-95c0-1c8cfcffb7c4
          stepCounter: 603404ec-df0e-46db-a2a5-81b34c4cb8a0
        config: {}
        dataType: VARCHAR(3)
        defaultValue: ""
        description: ""
        isSystemCurrentFlag: true
        name: DSS_CURRENT_FLAG
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f1722c48-c8d6-4650-8ce7-e07ed4626eae
                stepCounter: 103c2e43-fbba-4968-8290-2b2cc5127f13
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a6424b46-6b76-4223-a83a-8b9b7d157da5
          stepCounter: 603404ec-df0e-46db-a2a5-81b34c4cb8a0
        config: {}
        dataType: NUMBER(38)
        defaultValue: ""
        description: ""
        isSystemVersion: true
        name: DSS_VERSION
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 4390debb-5642-49a5-b181-503794d7fa6b
                stepCounter: 103c2e43-fbba-4968-8290-2b2cc5127f13
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: be2b469b-5e85-462b-9fe1-a341df116ca0
          stepCounter: 603404ec-df0e-46db-a2a5-81b34c4cb8a0
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: ""
        isSystemCreateDate: true
        name: DSS_CREATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c93286cd-5838-4ae1-b214-6d29ab05f5be
                stepCounter: 103c2e43-fbba-4968-8290-2b2cc5127f13
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 183d9559-c9b5-4c9b-92a5-7e37c09eaa12
          stepCounter: 603404ec-df0e-46db-a2a5-81b34c4cb8a0
        config: {}
        dataType: TIMESTAMP_NTZ(9)
        defaultValue: ""
        description: ""
        isSystemUpdateDate: true
        name: DSS_UPDATE_TIME
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f347d978-13a5-4f28-8a1b-75932b3ddf9e
                stepCounter: 103c2e43-fbba-4968-8290-2b2cc5127f13
            transform: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases: {}
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: DATA_LAKE
            nodeName: DL_DC81_DETAILSETTINGS
        join:
          joinCondition: FROM DATA_LAKE.MGA.dl_dc81_detailsettings dl_dc81_detailsettings
        name: V_DLBV_DC81_DETAILSETTINGS_CURRENT
        noLinkRefs: []
  name: V_DLBV_DC81_DETAILSETTINGS_CURRENT
  overrideSQL: false
  schema: ""
  sqlType: View
  type: sql
  version: 1
type: Node
