"""
gen_source_ddl.py  --  Emit CREATE TABLE DDL for every Source node.

Reads the generated + hand-built Source nodes (sqlType: Source) and writes a
Snowflake DDL file that creates each physical source table with its
reconstructed columns, in the database/schema its Coalesce location maps to
(from workspace.yml).  Run this so the BRONZE source tables physically exist,
then load data and run the pipeline.

Column types come straight from the node YAML (already Snowflake types).  For
parameterised IDMC sources these are best-effort reconstructions from mapping
usage, so review/adjust before loading production data.

Run:  python3 gen_source_ddl.py --repo ../.. --out ../ddl/02_source_tables.sql
"""
from __future__ import annotations
import argparse
import glob
import os
import yaml


DEFAULT_LOC = {"BRONZE": ("DOUG_POC", "ASCEND_BRONZE"),
               "SILVER": ("DOUG_POC", "ASCEND_SILVER"),
               "GOLD":   ("DOUG_POC", "ASCEND")}


def _location_map(repo_dir):
    """location -> (database, schema), from workspace.yml when present."""
    locs = dict(DEFAULT_LOC)
    wp = os.path.join(repo_dir, "workspace.yml")
    if os.path.exists(wp):
        try:
            data = yaml.safe_load(open(wp)) or {}
            for name, cfg in (data.get("locations") or {}).items():
                locs[name] = (cfg.get("database", "DOUG_POC"),
                              cfg.get("schema", name))
        except Exception:
            pass
    return locs


def _source_nodes(repo_dir):
    out = []
    for f in sorted(glob.glob(os.path.join(repo_dir, "nodes", "*.yml"))):
        d = yaml.safe_load(open(f))
        op = d.get("operation", {})
        if op.get("sqlType") == "Source":
            out.append(d)
    return out


def generate(repo_dir, out_path):
    locmap = _location_map(repo_dir)
    nodes = _source_nodes(repo_dir)

    # group by (database, schema)
    by_schema = {}
    for d in nodes:
        op = d["operation"]
        db, sch = locmap.get(op["locationName"], ("DOUG_POC", op["locationName"]))
        by_schema.setdefault((db, sch), []).append(d)

    lines = []
    lines.append("-- =====================================================================")
    lines.append("-- Source-table DDL  (Informatica IDMC -> Coalesce migration)")
    lines.append(f"-- Generated by gen_source_ddl.py from {len(nodes)} Source nodes.")
    lines.append("--")
    lines.append("-- Column types are reconstructed from IDMC mapping usage / embedded")
    lines.append("-- lookup schemas (the export carries no schema for parameterised")
    lines.append("-- sources).  Review before loading production data.")
    lines.append("-- =====================================================================")
    lines.append("")

    total = 0
    for (db, sch) in sorted(by_schema):
        lines.append(f"CREATE SCHEMA IF NOT EXISTS {db}.{sch};")
    lines.append("")

    for (db, sch) in sorted(by_schema):
        lines.append(f"-- ---------------------------------------------------------------------")
        lines.append(f"-- {db}.{sch}   ({len(by_schema[(db, sch)])} tables)")
        lines.append(f"-- ---------------------------------------------------------------------")
        for d in sorted(by_schema[(db, sch)], key=lambda x: x["name"]):
            op = d["operation"]
            cols = op.get("metadata", {}).get("columns", []) or []
            lines.append(f"CREATE OR REPLACE TABLE {db}.{sch}.\"{d['name']}\" (")
            coldefs = []
            for c in cols:
                dt = c.get("dataType") or "VARCHAR(256)"
                coldefs.append(f"    \"{c['name']}\" {dt}")
            if not coldefs:
                coldefs.append("    \"_PLACEHOLDER\" VARCHAR(256)")
            lines.append(",\n".join(coldefs))
            lines.append(");")
            lines.append("")
            total += 1

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out_path}: {total} tables across "
          f"{len(by_schema)} schema(s)")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    generate(args.repo, args.out)
